# These are supported funding model platforms

github: tylerebowers
custom: ["https://www.paypal.me/tylerebowers", "https://www.paypal.com/donate/?business=8VDFKHMBFSC2Q&no_recurring=0&currency_code=USD"]
